# AWSTemplateFormatVersion: "2010-09-09"
# Description: CloudFormation example template from Polynique
# Parameters:
#   Email:
#     Type: String
#     Default: pranavsharma.sre@gmail.com
#     Description: Email to receive S3 object created notification
#   BucketName:
#     Type: String
#     Default: pranavbucket-test
#     Description: Unique S3 bucket name
# Resources:
#   Bucket:
#     Type: AWS::S3::Bucket
#     Properties:
#       BucketName: !Ref BucketName
#       AccessControl: Private
#       PublicAccessBlockConfiguration:
#         BlockPublicAcls: True
#         BlockPublicPolicy: True
#         IgnorePublicAcls: True
#         RestrictPublicBuckets: True

AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation example template from Polynique
Parameters:
  Email:
    Type: String
    Default: pranavsharma.sre@gmail.com
    Description: Email to receive S3 object created notification
  BucketName:
    Type: String
    Default: pranavs-bucket
    Description: Unique S3 bucket name
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DependsOn:
      - SNSTopicPolicy
    Properties:
      BucketName: !Join ["-", [!Ref AWS::StackName, !Ref BucketName]]
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      NotificationConfiguration:
        TopicConfigurations:
          - Topic: !Ref Topic
            Event: s3:ObjectCreated:*
  MySqsQueue:
    Type: AWS::SQS::Queue
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join ["-", [!Ref AWS::StackName, "topic"]]
      TopicName: !Join ["-", [!Ref AWS::StackName, "topic"]]
      Subscription:
        - Protocol: email
          Endpoint: !Ref Email
        - Protocol: sqs
          Endpoint: !GetAtt MySqsQueue.Arn
  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sns:Publish
            Resource: !Ref Topic
            Condition:
              ArnLike:
                aws:SourceArn:
                  !Join [
                    "",
                    [
                      "arn:aws:s3:::",
                      !Join ["-", [!Ref AWS::StackName, !Ref BucketName]],
                    ],
                  ]
      Topics:
        - !Ref Topic
  SnsToSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "Allow SNS publish to SQS"
            Effect: Allow
            Principal: 
              Service: "sns.amazonaws.com"
            Resource: !GetAtt MySqsQueue.Arn
            Action: SQS:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref Topic
      Queues:
        - Ref: MySqsQueue

  SnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt Queue.Arn
      TopicArn: !Ref Topic
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      Role: !GetAtt LambdaFunctionRole.Arn
      Code:
        ZipFile: |
          var mysql = require('mysql');

          var connection = mysql.createConnection({
            host     : 'earth-daily-db.cltzlk5ou6cy.us-west-2.rds.amazonaws.com',
            user     : 'admin',
            password : 'earthdaily'
          });

          connection.connect();

          exports.handler = (event, context) => {
            try {
              connection.query("SELECT * FROM table", function(err, rows, fields) {
                  console.log('rows: ' + rows);
                  context.succeed('Success');
                });
              };
            }

          connection.query("SELECT * FROM table", function(err, rows, fields) {
            console.log('rows: ' + rows);
            context.succeed('Success');
            });
          };
  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: LambdaFunctionRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"

  # Allows SNS to call our Lambda function. as
  LambdaFunctionSNSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt LambdaFunction.Arn
      Principal: sns.amazonaws.com
      SourceArn:
        !Join
        - ''
        - - 'arn:'
          - !Ref AWS::Partition
          - ':sns:'
          - !Ref AWS::Region
          - ':'
          - !Ref AWS::AccountId
          - ':'
          - !Join ["-", [!Ref AWS::StackName, "topic"]]
