# AWSTemplateFormatVersion: "2010-09-09"
# Description: CloudFormation example template from Polynique
# Parameters:
#   Email:
#     Type: String
#     Default: pranavsharma.sre@gmail.com
#     Description: Email to receive S3 object created notification
#   BucketName:
#     Type: String
#     Default: pranavbucket-test
#     Description: Unique S3 bucket name
# Resources:
#   Bucket:
#     Type: AWS::S3::Bucket
#     Properties:
#       BucketName: !Ref BucketName
#       AccessControl: Private
#       PublicAccessBlockConfiguration:
#         BlockPublicAcls: True
#         BlockPublicPolicy: True
#         IgnorePublicAcls: True
#         RestrictPublicBuckets: True

AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CloudFormation example template from Polynique
Parameters:
  Email:
    Type: String
    Default: pranavsharma.sre@gmail.com
    Description: Email to receive S3 object created notification
  BucketName:
    Type: String
    Default: pranavs-bucket
    Description: Unique S3 bucket name
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DependsOn:
      - SNSTopicPolicy
    Properties:
      BucketName: !Join ["-", [!Ref AWS::StackName, !Ref BucketName]]
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      NotificationConfiguration:
        TopicConfigurations:
          - Topic: !Ref Topic
            Event: s3:ObjectCreated:*
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join ["-", [!Ref AWS::StackName, "topic"]]
      TopicName: !Join ["-", [!Ref AWS::StackName, "topic"]]
      Subscription:
        - Protocol: email
          Endpoint: !Ref Email
  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sns:Publish
            Resource: !Ref Topic
            Condition:
              ArnLike:
                aws:SourceArn:
                  !Join [
                    "",
                    [
                      "arn:aws:s3:::",
                      !Join ["-", [!Ref AWS::StackName, !Ref BucketName]],
                    ],
                  ]
      Topics:
        - !Ref Topic
  Backup:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-2:123456789012:applications/fork-event-storage-backup-pipeline
        SemanticVersion: 1.0.0
      Parameters: 
        #The ARN of the Amazon SNS topic whose messages should be backed up to the Amazon S3 bucket.
        TopicArn: !Ref Topic

  # # Allows SNS to call our Lambda function. as
  # LambdaFunctionSNSPermission:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     Action: lambda:InvokeFunction
  #     FunctionName: !GetAtt LambdaFunction.Arn
  #     Principal: sns.amazonaws.com
  #     SourceArn:
  #       !Join
  #       - ''
  #       - - 'arn:'
  #         - !Ref AWS::Partition
  #         - ':sns:'
  #         - !Ref AWS::Region
  #         - ':'
  #         - !Ref AWS::AccountId
  #         - ':'
  #         - !Join ["-", [!Ref AWS::StackName, "topic"]]
