# AWSTemplateFormatVersion: "2010-09-09"
# Description: CloudFormation example template from Polynique
# Parameters:
#   Email:
#     Type: String
#     Default: pranavsharma.sre@gmail.com
#     Description: Email to receive S3 object created notification
#   BucketName:
#     Type: String
#     Default: pranavbucket-test
#     Description: Unique S3 bucket name
# Resources:
#   Bucket:
#     Type: AWS::S3::Bucket
#     Properties:
#       BucketName: !Ref BucketName
#       AccessControl: Private
#       PublicAccessBlockConfiguration:
#         BlockPublicAcls: True
#         BlockPublicPolicy: True
#         IgnorePublicAcls: True
#         RestrictPublicBuckets: True

AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation example template from Polynique
Parameters:
  Email:
    Type: String
    Default: pranavsharma.sre@gmail.com
    Description: Email to receive S3 object created notification
  BucketName:
    Type: String
    Default: pranavs-bucket
    Description: Unique S3 bucket name
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DependsOn:
      - SNSTopicPolicy
    Properties:
      BucketName: !Join ["-", [!Ref AWS::StackName, !Ref BucketName]]
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      NotificationConfiguration:
        TopicConfigurations:
          - Topic: !Ref Topic
            Event: s3:ObjectCreated:*
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join ["-", [!Ref AWS::StackName, "topic"]]
      TopicName: !Join ["-", [!Ref AWS::StackName, "topic"]]
      Subscription:
        - Protocol: email
          Endpoint: !Ref Email
  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sns:Publish
            Resource: !Ref Topic
            Condition:
              ArnLike:
                aws:SourceArn:
                  !Join [
                    "",
                    [
                      "arn:aws:s3:::",
                      !Join ["-", [!Ref AWS::StackName, !Ref BucketName]],
                    ],
                  ]
      Topics:
        - !Ref Topic
